services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - redis-net

  # celery:
  #   build:
  #     context: .
  #     dockerfile: DockerfileCelery
  #   command: celery -A net2d worker --loglevel=INFO
  #   environment:
  #     - CELERY_BROKER=redis://redis:6379/0
  #     - CELERY_BACKEND=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #   restart: on-failure
  #   networks:
  #     - redis-net

  api:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - redis-net
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

networks:
  redis-net:
    # Specify driver options
    driver: bridge
